### PR TITLE
✅ Test Homebrew feature

### PR DESCRIPTION
**Pull request by andreiborisov**

### CODE REVIEW

**Comment by eitsupi** [comment]
I removed the code for alpine support as it did not seem to install git properly due to the code.
If you think alpine is worth supporting you can add it later. (assuming debian continues to pass the test)

**Comment by eitsupi** [comment]
Since alpine does not seem to be supported by Homebrew, it is recommended that alpine be removed from the baseImage of test.yaml and moved to the fish scenario test.

**Comment by eitsupi** [comment]
I would also recommend removing `brewPrefix` from the options as I see little value in making it an option.

**Comment by andreiborisov** [comment]
> Since Alpine does not seem to be supported by Homebrew, it is recommended that Alpine be removed from the baseImage of test.yaml and moved to the fish scenario test.

We can support Alpine, although it would require more work (I believe, we'll need to provide Ruby ourselves).

That being said, having the ability to use different base images for different features might come in handy by itself.

**Comment by andreiborisov** [comment]
> I would also recommend removing brewPrefix from the options as I see little value in making it an option.

Hmm, that makes sense, we always can add it later in case someone will ask for it.

**Pull request merged**
