### PR TITLE
fix: shallowclone option is not working

### PR DESCRIPTION
**Pull request by MrLuje**
Fixes https://github.com/meaningful-ooo/devcontainer-features/issues/50

### CODE REVIEW

**Review by eitsupi — CHANGES_REQUESTED** [review]
Thanks for working on this!
Could you bump the patch version here?
https://github.com/meaningful-ooo/devcontainer-features/blob/a10044f2ac392aca06fff212267a21eb6d8376a2/src/homebrew/devcontainer-feature.json#L4

**Review by eitsupi — APPROVED** [review]
The test failure is unrelated this PR.
(We need to fix the tests because the Dev Container CLI was updated a long time ago to run tests as a non-root user.)

**Comment by eitsupi** [comment]
The test fixes #52

**Comment by andreiborisov** [comment]
@MrLuje please, rebase on the latest commit from `main` to fix the tests 🙂

**Comment by MrLuje** [comment]
@andreiborisov rebase done, thanks

**Comment by eitsupi** [comment]
@MrLuje Could you squash the commits into one and rewrite the commit comment using 🐛 emoji instead of "fix: "?
Like this: https://github.com/meaningful-ooo/devcontainer-features/commit/cc1e0db9a5de872a0a746c2ab5380f7ac7959daf

**Comment by MrLuje** [comment]
@eitsupi done

**Comment by eitsupi** [comment]
Thanks @MrLuje, the new version has been published!

**Pull request merged**
